apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-hrjefa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-hrjefa
    app.kubernetes.io/part-of: jvm-build-suite-application-qwcz
  name: jvm-build-suite-component-hrjefa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-hrjefa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-hrjefa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-nbwa-tenant/jvm-build-suite-application-qwcz/jvm-build-suite-component-hrjefa@sha256:786ceab196b0b4b84648b25aed01989f114505a90d3aedaa723e8d2f8514460d
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
